#!/usr/bin/env node
// Build orchestrator: bundles the web UI, inlines it as one HTML string,
// writes that into src/cli/embedded.ts, then bundles the CLI binary.
import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import * as esbuild from "esbuild";

const root = path.dirname(fileURLToPath(import.meta.url));
const distWeb = path.join(root, "dist", "web");
const binDir = path.join(root, "bin");
const embeddedTs = path.join(root, "src", "cli", "embedded.ts");
const binOut = path.join(binDir, "diff-review.js");

async function main() {
  await fs.mkdir(distWeb, { recursive: true });
  await fs.mkdir(binDir, { recursive: true });

  // 1. Bundle the web UI (JS + CSS).
  console.log("[build] bundling web UI…");
  await esbuild.build({
    entryPoints: [path.join(root, "src/web/main.tsx")],
    bundle: true,
    minify: true,
    sourcemap: false,
    target: ["es2020"],
    format: "iife",
    outdir: distWeb,
    loader: { ".css": "css" },
    define: { "process.env.NODE_ENV": '"production"' },
    logLevel: "warning",
  });

  const js = await fs.readFile(path.join(distWeb, "main.js"), "utf8");
  const css = await fs.readFile(path.join(distWeb, "main.css"), "utf8");

  // 2. Compose a single self-contained HTML file.
  const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>diff-review</title>
<meta name="viewport" content="width=device-width,initial-scale=1">
<style>${css}</style>
</head>
<body>
<div id="root"></div>
<script>${js}</script>
</body>
</html>`;
  await fs.writeFile(path.join(distWeb, "index.html"), html, "utf8");

  // 3. Write src/cli/embedded.ts so the CLI bundler picks it up.
  const escaped = html
    .replace(/\\/g, "\\\\")
    .replace(/`/g, "\\`")
    .replace(/\$\{/g, "\\${");
  const embedded = `// AUTO-GENERATED by build.mjs. Do not edit by hand.\nexport const EMBEDDED_HTML = \`${escaped}\`;\n`;
  await fs.writeFile(embeddedTs, embedded, "utf8");

  // 4. Bundle the CLI binary.
  console.log("[build] bundling CLI…");
  await esbuild.build({
    entryPoints: [path.join(root, "src/cli/index.ts")],
    bundle: true,
    minify: false, // keep readable for debugging
    sourcemap: false,
    platform: "node",
    target: ["node20"],
    format: "esm",
    outfile: binOut,
    banner: { js: "#!/usr/bin/env node\n" },
    logLevel: "warning",
  });
  await fs.chmod(binOut, 0o755);

  const stat = await fs.stat(binOut);
  console.log(`[build] wrote ${path.relative(root, binOut)} (${(stat.size / 1024).toFixed(1)} KB)`);
}

main().catch((e) => {
  console.error("[build] failed:", e);
  process.exit(1);
});
